#!/bin/bash



rrdtool create veslefrikkTemp.rrd \
    --step '600' \
    'DS:Temperature_Cabin:GAUGE:300:-30:80' \
    'DS:Temperature_Engine:GAUGE:300:-30:100' \
    'DS:Temperature_Aft:GAUGE:300:-30:80' \
    'DS:Temperature_Outside:GAUGE:300:-30:80' \
    'RRA:AVERAGE:0.5:1:8640' \
    'RRA:AVERAGE:0.5:6:8640' \
    'RRA:MIN:0.5:6:8640' \
    'RRA:MAX:0.5:6:8640' \
    'RRA:AVERAGE:0.5:36:1440' \
    'RRA:MIN:0.5:36:1440' \
    'RRA:MAX:0.5:36:1440'

rrdtool create veslefrikkTemp.rrd ,
    --step "600" ,
    "DS:Temperature_Cabin:GAUGE:300:-30:80" ,
    "DS:Temperature_Engine:GAUGE:300:-30:100" ,
    "DS:Temperature_Aft:GAUGE:300:-30:80" ,
    "DS:Temperature_Outside:GAUGE:300:-30:80" ,
    "RRA:AVERAGE:0.5:1:8640" ,
    "RRA:AVERAGE:0.5:6:8640" ,
    "RRA:MIN:0.5:6:8640" ,
    "RRA:MAX:0.5:6:8640" ,
    "RRA:AVERAGE:0.5:36:1440" ,
    "RRA:MIN:0.5:36:1440" ,
    "RRA:MAX:0.5:36:1440"

        RRDs::create ($fname,
                      "--start", $start,
                      "--step", "300",
                      "DS:lat:GAUGE:600:-90:90",
                      "DS:lon:GAUGE:600:-180:180",
                      "DS:CS-T1T3:GAUGE:600:0:100000",
                      "DS:CS-T2T4:GAUGE:600:0:100000",
                      "DS:LOSS:GAUGE:600:0:100000",
                      "RRA:LAST:0.5:1:8064",
                      "RRA:MIN:0.5:12:8640",
                      "RRA:MAX:0.5:12:8640",
                      "RRA:AVERAGE:0.5:12:8640",
                      "RRA:AVERAGE:0.5:72:1440",
                      "RRA:AVERAGE:0.5:144:720",
                      "RRA:AVERAGE:0.5:288:360");



